### ISSUE TITLE
Code paragraphs look terrible in markdown-mode

### ISSUE THREAD

**Issue by rexim** [rexim/gruber-darker-theme#14]
![2017-07-25-131438_761x547_scrot](https://user-images.githubusercontent.com/165283/28558252-50aaef66-713b-11e7-95c0-39b30820df7a.png)

It feels like they are trying to modify the font. I think we can fix that on the theme level.

**Comment by jrblevin** [comment]
Code blocks in markdown-mode now inherit from `fixed-pitch`. You can choose another font for that face if you like, but the idea is that users probably want code to be in a fixed with font even if they use variable width font elsewhere.

**Comment by rexim** [comment]
@jrblevin Thanks for sharing this information! I'll see how we can better collaborate with markdown-mode. :)

**Comment by rexim** [comment]
Oh wow! That took me a really long time to realize that this is something that should be fixed on my side. https://github.com/rexim/dotfiles/commit/f305b310bafa89131b68a856a8bd5813f01788d8
